"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireStaffSession } from "@/lib/auth";
import { hashPassword } from "@/lib/password";
import { createDefaultCrmSetup } from "@/lib/tenant-setup";
import { ACCOUNT_LIFECYCLE_STAGES } from "@/lib/enums";

export async function moveAccountStage(accountId: string, newStage: string) {
  await requireStaffSession();
  const valid = ACCOUNT_LIFECYCLE_STAGES.some((s) => s.key === newStage);
  if (!valid) return;

  const account = await prisma.account.findUnique({ where: { id: accountId } });
  if (!account) return;

  await prisma.account.update({
    where: { id: accountId },
    data: {
      lifecycleStage: newStage,
      lifecycleEnteredAt: new Date(),
      status: newStage === "LOST" ? "ARCHIVED" : account.status,
      adsLive: newStage === "ADS_LIVE" || newStage === "RETAINED" ? true : account.adsLive,
    },
  });

  await prisma.activityLogEntry.create({
    data: {
      accountId,
      type: "UPDATED",
      message: `Ügyfél átkerült a "${ACCOUNT_LIFECYCLE_STAGES.find((s) => s.key === newStage)?.label}" szakaszba`,
    },
  });

  revalidatePath("/admin/ugyfelek");
  revalidatePath(`/admin/ugyfelek/${accountId}`);
}

export async function createAccountAction(formData: FormData) {
  const session = await requireStaffSession();
  const name = String(formData.get("name") ?? "").trim();
  if (!name) return;

  const account = await prisma.account.create({
    data: {
      organizationId: session.organizationId,
      name,
      website: String(formData.get("website") ?? "") || null,
      industry: String(formData.get("industry") ?? "") || null,
      monthlyFee: Number(formData.get("monthlyFee") ?? 0),
      setupFee: Number(formData.get("setupFee") ?? 0),
      monthlyAdBudget: Number(formData.get("monthlyAdBudget") ?? 0),
      source: String(formData.get("source") ?? "") || null,
    },
  });

  await createDefaultCrmSetup(account.id);

  await prisma.task.create({
    data: {
      organizationId: session.organizationId,
      accountId: account.id,
      title: `Új ügyfeled van: ${account.name}`,
      description: "Vedd fel a kapcsolatot és indítsd el az onboardingot.",
      category: "Egyéb",
      priority: "MEDIUM",
      assigneeId: session.teamMemberId,
      statusColumn: "ASSIGNED",
      autoGenerated: true,
    },
  });

  await prisma.activityLogEntry.create({
    data: { accountId: account.id, type: "CREATED", message: "Ügyfél létrehozva" },
  });

  revalidatePath("/admin/ugyfelek");
  redirect(`/admin/ugyfelek/${account.id}`);
}

export async function updateAccountDetailsAction(accountId: string, formData: FormData) {
  await requireStaffSession();

  const data: Record<string, unknown> = {};
  for (const key of ["website", "industry", "source"] as const) {
    const v = formData.get(key);
    if (v !== null) data[key] = String(v) || null;
  }
  for (const key of ["monthlyFee", "setupFee", "monthlyAdBudget"] as const) {
    const v = formData.get(key);
    if (v !== null) data[key] = Number(v);
  }
  if (formData.has("isTestAccountField")) {
    data.isTestAccount = formData.get("isTestAccount") === "on";
  }

  await prisma.account.update({ where: { id: accountId }, data });
  revalidatePath(`/admin/ugyfelek/${accountId}`);
}

export async function updateCrmSettingsAction(accountId: string, formData: FormData) {
  await requireStaffSession();
  await prisma.account.update({
    where: { id: accountId },
    data: {
      nameFormat: formData.get("nameFormat") === "EN" ? "EN" : "HU",
      callButtonEnabled: formData.get("callButtonEnabled") === "on",
    },
  });
  revalidatePath(`/admin/ugyfelek/${accountId}`);
  revalidatePath("/portal");
}

export async function updateFeatureFlagsAction(accountId: string, formData: FormData) {
  await requireStaffSession();
  const flags = {
    crm: formData.get("crm") === "on",
    calendar: formData.get("calendar") === "on",
    chatGptAdsTab: formData.get("chatGptAdsTab") === "on",
  };
  await prisma.account.update({ where: { id: accountId }, data: { featureFlags: JSON.stringify(flags) } });
  revalidatePath(`/admin/ugyfelek/${accountId}`);
}

export async function archiveAccountAction(accountId: string) {
  await requireStaffSession();
  await prisma.account.update({ where: { id: accountId }, data: { status: "ARCHIVED", lifecycleStage: "LOST" } });
  revalidatePath("/admin/ugyfelek");
  redirect("/admin/ugyfelek");
}

export async function deleteAccountAction(accountId: string) {
  await requireStaffSession();
  await prisma.account.delete({ where: { id: accountId } });
  revalidatePath("/admin/ugyfelek");
  redirect("/admin/ugyfelek");
}

export async function changePortalPasswordAction(accountId: string, formData: FormData) {
  await requireStaffSession();
  const contactId = String(formData.get("contactId") ?? "");
  const newPassword = String(formData.get("newPassword") ?? "");
  if (!contactId || newPassword.length < 4) return;
  const hash = await hashPassword(newPassword);
  await prisma.contact.update({ where: { id: contactId }, data: { passwordHash: hash, canLoginPortal: true } });
  revalidatePath(`/admin/ugyfelek/${accountId}`);
}

export async function addContactAction(accountId: string, formData: FormData) {
  await requireStaffSession();
  const fullName = String(formData.get("fullName") ?? "").trim();
  if (!fullName) return;
  await prisma.contact.create({
    data: {
      accountId,
      fullName,
      email: String(formData.get("email") ?? "") || null,
      phone: String(formData.get("phone") ?? "") || null,
      position: String(formData.get("position") ?? "") || null,
      isPrimary: false,
    },
  });
  revalidatePath(`/admin/ugyfelek/${accountId}`);
}

export async function setTeamAssignmentAction(accountId: string, formData: FormData) {
  await requireStaffSession();
  const role = String(formData.get("role") ?? "");
  const teamMemberId = String(formData.get("teamMemberId") ?? "");
  if (!role) return;

  await prisma.teamAssignment.deleteMany({ where: { accountId, role } });
  if (teamMemberId) {
    await prisma.teamAssignment.create({ data: { accountId, role, teamMemberId } });
  }
  revalidatePath(`/admin/ugyfelek/${accountId}`);
}

export async function addAccountNoteAction(accountId: string, formData: FormData) {
  const session = await requireStaffSession();
  const body = String(formData.get("body") ?? "").trim();
  if (!body) return;
  await prisma.activityLogEntry.create({
    data: { accountId, actorId: session.teamMemberId, type: "NOTE_ADDED", message: body },
  });
  revalidatePath(`/admin/ugyfelek/${accountId}`);
}

export async function addCredentialAction(accountId: string, formData: FormData) {
  await requireStaffSession();
  const label = String(formData.get("label") ?? "").trim();
  const value = String(formData.get("value") ?? "").trim();
  if (!label || !value) return;
  await prisma.credential.create({ data: { accountId, label, value } });
  revalidatePath(`/admin/ugyfelek/${accountId}`);
}
